### imports and installs

In [1]:
!pip install ultralytics
from IPython.display import clear_output
clear_output()

In [2]:
import os
from ultralytics import YOLO
import cv2
import numpy as np

Setting the paths for image and model

In [3]:
cwd = os.getcwd()
cwd

'/home/ec2-user/SageMaker'

In [4]:
#getting model from train17
model_path=cwd+'/runs/pose/train17/weights/best.pt'

In [5]:
image_path=cwd+'/dataset_1/images/val/25debad9ccacdc856d29b149e5802415330870e4c9f61489bfc1b1f88a5c5f41.jpg'

In [6]:
#importng the model
model = YOLO(model_path)
model

In [7]:
#running the model on the image and getting predictions
results=model(image_path)


image 1/1 /home/ec2-user/SageMaker/dataset_1/images/val/25debad9ccacdc856d29b149e5802415330870e4c9f61489bfc1b1f88a5c5f41.jpg: 480x640 2 fuse_blocks, 62.6ms
Speed: 175.0ms preprocess, 62.6ms inference, 530.7ms postprocess per image at shape (1, 3, 480, 640)


In [8]:
len(results)

1

Getting the array of key points prdicted for the image ###  kpt1 (torch.Tensor): A tensor of shape (N, 20, 3) representing ground truth keypoints.
        kpt2 (torch.Tensor): A tensor of shape (M, 20, 3) representing predicted keypoints.

In [9]:
for result in results:
    boxes = result.boxes  # Boxes object for bbox outputs
    print(boxes)
    print("_________________________")
    keypoints = result.keypoints  # Keypoints object for pose outputs
    print(keypoints)
    print("_________________________")
    probs = result.probs
    print(probs)
    

WARNING ⚠️ 'Boxes.boxes' is deprecated. Use 'Boxes.data' instead.


ultralytics.engine.results.Boxes object with attributes:

boxes: tensor([[412.0000, 591.0000, 567.0000, 687.0000,   0.8801,   0.0000],
        [404.0000, 465.0000, 561.0000, 564.0000,   0.8712,   0.0000]], device='cuda:0')
cls: tensor([0., 0.], device='cuda:0')
conf: tensor([0.8801, 0.8712], device='cuda:0')
data: tensor([[412.0000, 591.0000, 567.0000, 687.0000,   0.8801,   0.0000],
        [404.0000, 465.0000, 561.0000, 564.0000,   0.8712,   0.0000]], device='cuda:0')
id: None
is_track: False
orig_shape: (960, 1280)
shape: torch.Size([2, 6])
xywh: tensor([[489.5000, 639.0000, 155.0000,  96.0000],
        [482.5000, 514.5000, 157.0000,  99.0000]], device='cuda:0')
xywhn: tensor([[0.3824, 0.6656, 0.1211, 0.1000],
        [0.3770, 0.5359, 0.1227, 0.1031]], device='cuda:0')
xyxy: tensor([[412., 591., 567., 687.],
        [404., 465., 561., 564.]], device='cuda:0')
xyxyn: tensor([[0.3219, 0.6156, 0.4430, 0.7156],
        [0.3156, 0.4844, 0.4383, 0.5875]], device='cuda:0')
_________________

In [10]:
results[0].boxes

WARNING ⚠️ 'Boxes.boxes' is deprecated. Use 'Boxes.data' instead.


ultralytics.engine.results.Boxes object with attributes:

boxes: tensor([[412.0000, 591.0000, 567.0000, 687.0000,   0.8801,   0.0000],
        [404.0000, 465.0000, 561.0000, 564.0000,   0.8712,   0.0000]], device='cuda:0')
cls: tensor([0., 0.], device='cuda:0')
conf: tensor([0.8801, 0.8712], device='cuda:0')
data: tensor([[412.0000, 591.0000, 567.0000, 687.0000,   0.8801,   0.0000],
        [404.0000, 465.0000, 561.0000, 564.0000,   0.8712,   0.0000]], device='cuda:0')
id: None
is_track: False
orig_shape: (960, 1280)
shape: torch.Size([2, 6])
xywh: tensor([[489.5000, 639.0000, 155.0000,  96.0000],
        [482.5000, 514.5000, 157.0000,  99.0000]], device='cuda:0')
xywhn: tensor([[0.3824, 0.6656, 0.1211, 0.1000],
        [0.3770, 0.5359, 0.1227, 0.1031]], device='cuda:0')
xyxy: tensor([[412., 591., 567., 687.],
        [404., 465., 561., 564.]], device='cuda:0')
xyxyn: tensor([[0.3219, 0.6156, 0.4430, 0.7156],
        [0.3156, 0.4844, 0.4383, 0.5875]], device='cuda:0')

In [11]:
results[0].keypoints

ultralytics.engine.results.Keypoints object with attributes:

conf: tensor([[9.1569e-01, 9.4305e-01, 9.4718e-01, 9.5455e-01, 9.4256e-01, 9.3398e-01, 9.2955e-01, 8.8639e-01, 1.7828e-03, 3.8250e-04, 9.1337e-01, 9.1913e-01, 9.3527e-01, 9.4529e-01, 9.4643e-01, 9.3883e-01, 9.2764e-01, 9.0341e-01, 4.2924e-03, 9.1525e-04],
        [9.4259e-01, 9.6104e-01, 9.6349e-01, 9.6903e-01, 9.5533e-01, 9.4561e-01, 9.3676e-01, 8.9347e-01, 1.5317e-03, 3.8471e-04, 9.4519e-01, 9.5694e-01, 9.6125e-01, 9.6927e-01, 9.6588e-01, 9.5943e-01, 9.4512e-01, 9.2387e-01, 4.4853e-03, 8.9082e-04]], device='cuda:0')
data: tensor([[[4.2930e+02, 6.7554e+02, 9.1569e-01],
         [4.4761e+02, 6.7602e+02, 9.4305e-01],
         [4.6354e+02, 6.7579e+02, 9.4718e-01],
         [4.8270e+02, 6.7639e+02, 9.5455e-01],
         [4.9646e+02, 6.7550e+02, 9.4256e-01],
         [5.1665e+02, 6.7575e+02, 9.3398e-01],
         [5.3167e+02, 6.7497e+02, 9.2955e-01],
         [5.4854e+02, 6.7485e+02, 8.8639e-01],
         [5.1577e+02, 6.7641e+02

In [12]:

a=results[0].keypoints
required=a.xyn
predicted_keypoints=required.tolist()
predicted_keypoints


[[[0.3353910446166992, 0.7036892771720886],
  [0.3496955931186676, 0.704188883304596],
  [0.3621443212032318, 0.7039445638656616],
  [0.37711280584335327, 0.7045750617980957],
  [0.3878600299358368, 0.703646183013916],
  [0.40363508462905884, 0.7039097547531128],
  [0.41537004709243774, 0.7030932903289795],
  [0.42854514718055725, 0.7029692530632019],
  [0.40294620394706726, 0.70458984375],
  [0.38063913583755493, 0.669111967086792],
  [0.3330655097961426, 0.6272857785224915],
  [0.34642738103866577, 0.6262938380241394],
  [0.36070820689201355, 0.6270750761032104],
  [0.3757418096065521, 0.6271369457244873],
  [0.38440388441085815, 0.6261534094810486],
  [0.40086886286735535, 0.6271564960479736],
  [0.4132861793041229, 0.6265015602111816],
  [0.42781296372413635, 0.6266894340515137],
  [0.4277052879333496, 0.7028643488883972],
  [0.4165502190589905, 0.7013018131256104]],
 [[0.3316112458705902, 0.5758517384529114],
  [0.345455139875412, 0.5761963725090027],
  [0.3583230674266815, 0.5755

In [13]:
print(len(predicted_keypoints[0]),len(predicted_keypoints[1]))

20 20


In [14]:
path3='/home/ec2-user/SageMaker/dataset_1/images/val/25debad9ccacdc856d29b149e5802415330870e4c9f61489bfc1b1f88a5c5f41.txt'
label=['0 0.378125 0.5390625 0.121875 0.096875 0.33340390625 0.5742635416666667 2 0.3467828125 0.5750447916666667 2 0.35938046875 0.5764770833333334 2 0.37129453125 0.5737427083333333 2 0.38555234375 0.5766072916666667 2 0.396978125 0.574784375 2 0.41133359374999995 0.5725708333333334 2 0.42393125 0.5758260416666666 2 0 0 0 0 0 0 0.3256890625 0.5005229166666667 2 0.339946875 0.4981791666666667 2 0.35391171875 0.4997416666666667 2 0.367290625 0.4989604166666667 2 0.38018125 0.4977885416666667 2 0.39414609375 0.49726770833333334 2 0.40791562499999995 0.4984395833333333 2 0.42070859374999997 0.5001322916666667 2 0 0 0 0 0 0', 
'0 0.381640625 0.6640625 0.11953125 0.10104166666666667 0.335259375 0.7038645833333333 2 0.34736875 0.7024760416666667 2 0.3622125 0.7040385416666666 2 0.37341015624999996 0.7047322916666666 2 0.38578046875 0.7061218749999999 2 0.399321875 0.7054270833333334 2 0.41104062499999994 0.70803125 2 0.42731640625 0.7064687500000001 2 0 0 0 0 0 0 0.33340390625 0.6222239583333333 2 0.3448296875 0.6237864583333333 2 0.357525 0.6226145833333334 2 0.3713921875 0.624046875 2 0.38379453125 0.627953125 2 0.39707578125 0.6262604166666667 2 0.41006406249999994 0.6246979166666667 2 0.42373593749999994 0.6245677083333334 2 0 0 0 0 0 0']

In [15]:
data=[]
bbx=[]
for i in label:
    k=[]
    for t in i.split(' '):
        k.append(float(t))
    j = k[5:]
    bb=k[0:5]
    data.append(j)
    bbx.append(bb)
GD_keypoints=[]
for i in data:
    l=[]
    for k in range(0,len(i)-2,3):
        t=[]
        t.append(i[k])
        t.append(i[k+1])
        l.append(t)
    GD_keypoints.append(l)
        
GD_keypoints   



[[[0.33340390625, 0.5742635416666667],
  [0.3467828125, 0.5750447916666667],
  [0.35938046875, 0.5764770833333334],
  [0.37129453125, 0.5737427083333333],
  [0.38555234375, 0.5766072916666667],
  [0.396978125, 0.574784375],
  [0.41133359374999995, 0.5725708333333334],
  [0.42393125, 0.5758260416666666],
  [0.0, 0.0],
  [0.0, 0.0],
  [0.3256890625, 0.5005229166666667],
  [0.339946875, 0.4981791666666667],
  [0.35391171875, 0.4997416666666667],
  [0.367290625, 0.4989604166666667],
  [0.38018125, 0.4977885416666667],
  [0.39414609375, 0.49726770833333334],
  [0.40791562499999995, 0.4984395833333333],
  [0.42070859374999997, 0.5001322916666667],
  [0.0, 0.0],
  [0.0, 0.0]],
 [[0.335259375, 0.7038645833333333],
  [0.34736875, 0.7024760416666667],
  [0.3622125, 0.7040385416666666],
  [0.37341015624999996, 0.7047322916666666],
  [0.38578046875, 0.7061218749999999],
  [0.399321875, 0.7054270833333334],
  [0.41104062499999994, 0.70803125],
  [0.42731640625, 0.7064687500000001],
  [0.0, 0.0],
  

In [16]:
print(len(GD_keypoints[0]),len(GD_keypoints[1]))

20 20


Running validation on the same image and getting mAP scores

In [17]:
val_results=model.val()

Ultralytics YOLOv8.0.151 🚀 Python-3.10.10 torch-2.0.0 CUDA:0 (Tesla T4, 15102MiB)
100%|██████████| 755k/755k [00:00<00:00, 84.7MB/s]
val: Scanning /home/ec2-user/SageMaker/dataset_1/labels/val.cache... 1 images, 0 backgrounds, 0 corrupt: 100%|██████████| 1/1 [00:00<?, ?it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Pose(P          R      mAP50  mAP50-95): 100%|██████████| 1/1 [00:03<00:00,  3.50s/it]
                   all          1          2          1          1      0.995      0.958          1          1      0.995      0.834
Speed: 0.4ms preprocess, 65.8ms inference, 0.0ms loss, 0.8ms postprocess per image
Results saved to runs/pose/val9


In [18]:
val_results.results_dict

{'metrics/precision(B)': 1.0,
 'metrics/recall(B)': 1.0,
 'metrics/mAP50(B)': 0.995,
 'metrics/mAP50-95(B)': 0.9577500000000001,
 'metrics/precision(P)': 1.0,
 'metrics/recall(P)': 1.0,
 'metrics/mAP50(P)': 0.995,
 'metrics/mAP50-95(P)': 0.8335000000000001,
 'fitness': 1.8111250000000003}

Step1 = Euclidian distance, findout the Euclidian distance between two corresponding points

In [19]:
import math

def euclidean_distance(x1:float, y1:float,  x2:float, y2: float):
    return math.sqrt((x2 - x1)**2 + (y2 - y1)**2)

# Example coordinates
x1 = 1
y1 = 2
x2 = 4
y2 = 6

distance = euclidean_distance(x1, y1, x2, y2)
print(f"The Euclidean distance between points P({x1}, {y1}) and Q({x2}, {y2}) is {distance:.2f}")

The Euclidean distance between points P(1, 2) and Q(4, 6) is 5.00


In [20]:
Euclidian_distance=[]
for k in range(len(predicted_keypoints)):
    l=[]
    pred_keypoints=predicted_keypoints[k]
    gd_keypoints=GD_keypoints[k]
    for j in range(len(pred_keypoints)):
        pred_keypoint=pred_keypoints[j]
        gd_keypoint=gd_keypoints[j]
        #print( pred_keypoint)
        #print(gd_keypoint)
        ED=euclidean_distance(pred_keypoint[0],pred_keypoint[1] , gd_keypoint[0], gd_keypoint[1])
        l.append(ED)
    Euclidian_distance.append(l)
Euclidian_distance      

[[0.12944098937356682,
  0.12917693561901197,
  0.12749744104742933,
  0.13096166245268953,
  0.1270598494028327,
  0.12929686310150182,
  0.13058485645650483,
  0.1272269006594785,
  0.8116726502667199,
  0.7698032061701983,
  0.12697730159596116,
  0.12827847042879187,
  0.12751466350894325,
  0.1284548368982825,
  0.12843430200056175,
  0.13006264951393293,
  0.12817454027768577,
  0.12675638982452853,
  0.822769777194362,
  0.8156827312695553],
 [0.12806481679416806,
  0.12629416750696762,
  0.12852020902378777,
  0.12921351904356726,
  0.13199811900308508,
  0.1310197039542026,
  0.1341789524275625,
  0.13309317986827363,
  0.7020398456392265,
  0.6475452078489408,
  0.12307138356938528,
  0.1258559527353371,
  0.12437742955726447,
  0.1258686323714247,
  0.130718433829491,
  0.12920084598303264,
  0.12795263629076578,
  0.1279334009512709,
  0.7136748282765766,
  0.7061743455733284]]

In [21]:
import numpy as np
np.asarray(Euclidian_distance).shape

(2, 20)

Step2 sigma

In [22]:
sigma=[1/20 for i in GD_keypoints[0]]
len(sigma)

20

In [23]:
sigma

[0.05,
 0.05,
 0.05,
 0.05,
 0.05,
 0.05,
 0.05,
 0.05,
 0.05,
 0.05,
 0.05,
 0.05,
 0.05,
 0.05,
 0.05,
 0.05,
 0.05,
 0.05,
 0.05,
 0.05]

Step 3 Area: area (torch.Tensor): A tensor of shape (N,) representing areas from ground truth.
bbx

In [24]:
bbx

[[0.0, 0.378125, 0.5390625, 0.121875, 0.096875],
 [0.0, 0.381640625, 0.6640625, 0.11953125, 0.10104166666666667]]

In [27]:
area=[]
for i in bbx:
    a=i[3]*i[4]
    area.append(a)
area = torch.tensor(area)
area

tensor([0.0118, 0.0121])

In [28]:
import torch

# Convert to a PyTorch tensor
kpt1 = torch.tensor(GD_keypoints)

print("PyTorch Tensor:")
print(kpt1)

PyTorch Tensor:
tensor([[[0.3334, 0.5743],
         [0.3468, 0.5750],
         [0.3594, 0.5765],
         [0.3713, 0.5737],
         [0.3856, 0.5766],
         [0.3970, 0.5748],
         [0.4113, 0.5726],
         [0.4239, 0.5758],
         [0.0000, 0.0000],
         [0.0000, 0.0000],
         [0.3257, 0.5005],
         [0.3399, 0.4982],
         [0.3539, 0.4997],
         [0.3673, 0.4990],
         [0.3802, 0.4978],
         [0.3941, 0.4973],
         [0.4079, 0.4984],
         [0.4207, 0.5001],
         [0.0000, 0.0000],
         [0.0000, 0.0000]],

        [[0.3353, 0.7039],
         [0.3474, 0.7025],
         [0.3622, 0.7040],
         [0.3734, 0.7047],
         [0.3858, 0.7061],
         [0.3993, 0.7054],
         [0.4110, 0.7080],
         [0.4273, 0.7065],
         [0.0000, 0.0000],
         [0.0000, 0.0000],
         [0.3334, 0.6222],
         [0.3448, 0.6238],
         [0.3575, 0.6226],
         [0.3714, 0.6240],
         [0.3838, 0.6280],
         [0.3971, 0.6263],
         [

In [29]:
kpt2=torch.tensor(predicted_keypoints)
kpt2

tensor([[[0.3354, 0.7037],
         [0.3497, 0.7042],
         [0.3621, 0.7039],
         [0.3771, 0.7046],
         [0.3879, 0.7036],
         [0.4036, 0.7039],
         [0.4154, 0.7031],
         [0.4285, 0.7030],
         [0.4029, 0.7046],
         [0.3806, 0.6691],
         [0.3331, 0.6273],
         [0.3464, 0.6263],
         [0.3607, 0.6271],
         [0.3757, 0.6271],
         [0.3844, 0.6262],
         [0.4009, 0.6272],
         [0.4133, 0.6265],
         [0.4278, 0.6267],
         [0.4277, 0.7029],
         [0.4166, 0.7013]],

        [[0.3316, 0.5759],
         [0.3455, 0.5762],
         [0.3583, 0.5756],
         [0.3736, 0.5755],
         [0.3838, 0.5741],
         [0.4000, 0.5744],
         [0.4119, 0.5739],
         [0.4248, 0.5734],
         [0.4004, 0.5767],
         [0.3691, 0.5320],
         [0.3276, 0.4993],
         [0.3415, 0.4980],
         [0.3561, 0.4982],
         [0.3717, 0.4982],
         [0.3801, 0.4973],
         [0.3970, 0.4971],
         [0.4094, 0.4967],

In [36]:
def kpt_iou(y, kpt2, area, sigma, eps=1e-7):
    """
    Calculate Object Keypoint Similarity (OKS).

    Args:
        kpt1 (torch.Tensor): A tensor of shape (N, 17, 3) representing ground truth keypoints.
        kpt2 (torch.Tensor): A tensor of shape (M, 17, 3) representing predicted keypoints.
        area (torch.Tensor): A tensor of shape (N,) representing areas from ground truth.
        sigma (list): A list containing 17 values representing keypoint scales.
        eps (float, optional): A small value to avoid division by zero. Defaults to 1e-7.

    Returns:
        (torch.Tensor): A tensor of shape (N, M) representing keypoint similarities.
    """
    d = (kpt1[:, None, :, 0] - kpt2[..., 0]) ** 2 + (kpt1[:, None, :, 1] - kpt2[..., 1]) ** 2  # (N, M, 17)
    sigma = torch.tensor(sigma, device=kpt1.device, dtype=kpt1.dtype)  # (17, )
    kpt_mask = kpt1[..., 1] != 0  # (N, 17)
    e = d / (2 * sigma) ** 2 / (area[:, None, None] + eps) / 2  # from cocoeval
    # e = d / ((area[None, :, None] + eps) * sigma) ** 2 / 2  # from formula
    return (torch.exp(-e) * kpt_mask[:, None]).sum(-1) / (kpt_mask.sum(-1)[:, None] + eps)

In [37]:
iou=kpt_iou(kpt1, kpt2, area, sigma, eps=1e-7)
iou

tensor([[8.7652e-31, 9.7071e-01],
        [9.3668e-01, 5.2603e-29]])

In [38]:
area

tensor([0.0118, 0.0121])

In [39]:
kpt_mask = kpt1[..., 1] != 0

In [40]:
kpt_mask[:, None]

tensor([[[ True,  True,  True,  True,  True,  True,  True,  True, False, False,  True,  True,  True,  True,  True,  True,  True,  True, False, False]],

        [[ True,  True,  True,  True,  True,  True,  True,  True, False, False,  True,  True,  True,  True,  True,  True,  True,  True, False, False]]])